version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi
      - redis-admin
    networks:
      - celery-network

  fastapi:
    build: .
    environment:
      - REDIS_URL=redis://redis:6379/0
      - FASTAPI_HOST=0.0.0.0
      - FASTAPI_PORT=8000
    volumes:
      - ./app:/app
    depends_on:
      - redis
    networks:
      - celery-network

  celery-worker:
    build: .
    command: celery -A tasks:celery_app worker --loglevel=info --pool=solo
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./app:/app
    depends_on:
      - redis
      - fastapi
    networks:
      - celery-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - celery-network

  redis-admin:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - celery-network

volumes:
  redis-data:

networks:
  celery-network:
    driver: bridge